---
- name: Install software (apt-get)
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - wireshark
    - hachoir
    - gcc
    - gdb
    - nmap
    - hopper
    - vim
    - emacs
    - python
    - wget
    - curl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- yum: name={{ item }} state=latest
  with_items:
    - wireshark
    - hachoir
    - gcc
    - gdb
    - nmap
    - hopper
    - vim
    - emacs
    - python
    - wget
    - curl
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
